### ISSUE TITLE
Cannot reproduce handpose in x86 platform

### ISSUE THREAD

**Issue by AlexTraan** [terryky/tflite_gles_app#1]
Hi Author,

Thank you for your valuable repository.

I am trying to reproduce your handpose for x86 platform, but when i build, i faced error as below:
"In file included from tflite_handpose.cpp:5:0:
../common/util_tflite.h:8:46: fatal error: tensorflow/lite/kernels/register.h: No such file or directory
compilation terminated.
../Makefile.include:18: recipe for target 'tflite_handpose.o' failed
make: *** [tflite_handpose.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from custom_ops/transpose_conv_bias.cc:19:0:
custom_ops/transpose_conv_bias.h:18:52: fatal error: tensorflow/lite/kernels/internal/types.h: No such file or directory
compilation terminated.
../Makefile.include:21: recipe for target 'custom_ops/transpose_conv_bias.o' failed
make: *** [custom_ops/transpose_conv_bias.o] Error 1
In file included from ../common/util_tflite.cpp:5:0:
../common/util_tflite.h:8:46: fatal error: tensorflow/lite/kernels/register.h: No such file or directory"

It quite strange when that path ( tensorflow/lite/kernels/register.h,...) existed.

Can you help?

**Comment by terryky** [comment]
Hi AlexTraan san,

Did you run the script below ?
```
$ cd ~/work
$ ./tflite_gles_app/tools/scripts/tf2.2/build_libtflite_r2.2.sh
$ ln -s tensorflow_r2.2 ./tensorflow
```

And then, please confirm if the header file exists at ```~/work/tensorflow/tensorflow/lite/kernels/register.h```.

**Comment by AlexTraan** [comment]
Hi Yoshiteru san,

Thank you for your feedback.

"Did you run the script below ?"
>> yes, i have followed your guidance.

"And then, please confirm if the header file exists at ~/work/tensorflow/tensorflow/lite/kernels/register.h."
>> I not created "~/work" folder, downloaded tensorflow folder put in "tflite_gles_app/tools/scripts/tf2.2" folder

**Comment by terryky** [comment]
Please reopen if problem still exists.
