### ISSUE TITLE
failed to compile vertex shader !

### ISSUE THREAD

**Issue by satyajitghana** [terryky/tflite_gles_app#11]
Hey, i've been trying to get the examples to work on a Jetson Nano, but i'm getting the below error

![image](https://user-images.githubusercontent.com/8092481/97987776-df97cc00-1e01-11eb-9596-94d14cd5ab94.png)

and i have no clue what this might be related to, the above is trying to run `gl2facemesh`

compile command: `make -j4 TARGET_ENV=jetson_nano TFLITE_DELEGATE=GPU_DELEGATEV2 ENABLE_IMGUI=true ENABLE_VDEC=true`

i've try to enable/disable `IMGUI` and `VDEC` option, but same error pops up

**Comment by satyajitghana** [comment]
nevermind, my bad, i was using vnc connection, and opengl wasn't working

**Comment by quhb2455** [comment]
hi @satyajitghana 
thank you for your self answer
i got same error with you
how can i solve it?
and what is meaning of "the opengl wan't working"?
thank you

**Comment by satyajitghana** [comment]
@quhb2455 when using a VNC connected OpenGL wasn't supported, i.e. the render engine doesn't use OpenGL, so i was getting that error.

see if you can get `glxgears` to run, if it does, then opengl is working.
