### ISSUE TITLE
[Iris Tracker] right eye keypoints should be flipped

### ISSUE THREAD

**Issue by FrankSpalteholz** [terryky/tflite_gles_app#14]
First of all this is a great repo and I've learned a lot from it towards using TF and Mediapipe so thank you very much. I realized that the keypoints of the right eye should be flipped (1f-pos.x for all keypoints from output). But just more nitpicking then having a real issue to mention.

**Comment by terryky** [comment]
Thanks for pointing that out. I will investigate.

**Comment by terryky** [comment]
I've fixed this issue. 
Thanks again for pointing this out.

- Before
![before](https://user-images.githubusercontent.com/40374465/99146712-e655f700-26bd-11eb-9433-92cc0b057e9c.jpg)
- After
![after](https://user-images.githubusercontent.com/40374465/99146715-ebb34180-26bd-11eb-9a65-45721d71258c.jpg)

**Comment by FrankSpalteholz** [comment]
You're very welcome!
