### ISSUE TITLE
Feasibility for Python version

### ISSUE THREAD

**Issue by AlexTraan** [terryky/tflite_gles_app#2]
Hi Terryky san,

Thank you for your value repository.

I'd like to ask you about the feasibility of convert from current C/C++ version to Python version?
Is it difficult?

Thank you for your expertise

**Comment by terryky** [comment]
Hi AlexTraan san,

Technically, I think it is possible to rewrite the current code in python.
Whether it is difficult or not depends on your technical skills.

**Comment by AlexTraan** [comment]
Hi Terryky san,

I got it.

Thank you for your feedback.
