### ISSUE TITLE
libEGL warning: DRI2: failed to create any config

### ISSUE THREAD

**Issue by quhb2455** [terryky/tflite_gles_app#21]
hi!

i got some error when i inference gl2pose_estimation_3d with video file

build with video option is okay

but i inference gl2pose_estimation_3d
`./gl2pose_estimation_3d -v ./testVideo_6.mp4`

i got 
```
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
ERR: /workspace/workspace/tflite_gles_app/common/util_egl.c(316)
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:186) : Failed to compile shader.
ERR: /workspace/workspace/tflite_gles_app/common/util_render2d.c(319)
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:69) : Error: problem compiling shader.
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:70) : -----------------------------------
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:71) : ▒;Y
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:72) : -----------------------------------
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:69) : Error: problem compiling shader.
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:70) : -----------------------------------
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:71) :
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:72) : -----------------------------------
ERROR(/workspace/workspace/tflite_gles_app/common/util_shader.c:186) : Failed to compile shader.
```
and 
```
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader!
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 100
')
```
my environment is 
```
ubuntu 16.04
ffmpeg version 4.3.2-0york0~16.04 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
```

how can i solve it?

**Comment by terryky** [comment]
Are you running the app via ssh or vnc ?
if so, could you run the app on native console ?

**Comment by quhb2455** [comment]
hi @terryky ! 
thank you for reply my question.

i already see #11 error and then i tried to run it on native console but still doesn't work.

actually i use a docker. Is this error because of docker?

**Comment by terryky** [comment]
I suspect your docker environment doesn't allow to use OpenGL. 
can you run ```glxinfo``` and/or ```glxgears``` in your docker environment ?

[this article](https://medium.com/@benjamin.botto/opengl-and-cuda-applications-in-docker-af0eece000f1) might help you.

**Comment by quhb2455** [comment]
hi, @terryky 

i tried what you are advice, but it doesn't work for me.

so i guess that the problem comes from docker environment.
i will try to make docker to use OpenGL and if it still doesn't work i am going to reopen this issue.

Thank you for helping me!
