### ISSUE TITLE
undefined reference to 'update_video_texture', undefined reference to 'create_video_texture'

### ISSUE THREAD

**Issue by laolihaile** [terryky/tflite_gles_app#22]
I want to use a recorded video,
When I execute the following command
`make -j4 ENABLE_VDEC=true`
I get the following error:
ur/work/tflite_gles_app/gl2blazeface/main.c:308:undefined reference to 'update_video_texture'
ur/work/tflite_gles_app/gl2blazeface/main.c:257:undefined reference to 'create_video_texture'
when i make other apps, the same problem comes up
How should I solve it please?

**Comment by terryky** [comment]
try `make clean; make -j4 ENABLE_VDEC=true`

**Comment by laolihaile** [comment]
> try `make clean; make -j4 ENABLE_VDEC=true`

thank you very much
