### ISSUE TITLE
error in record video 

### ISSUE THREAD

**Issue by laolihaile** [terryky/tflite_gles_app#23]
[swscaler @ 0x7f8c000f60] No accelerated colorspace conversion found from yuv420p to rgb24.
how should i sovle it please?

**Comment by laolihaile** [comment]
> [swscaler @ 0x7f8c000f60] No accelerated colorspace conversion found from yuv420p to rgb24.
> how should i sovle it please?

A black screen appears and no picture is displayed

**Comment by terryky** [comment]
I can't reproduce the phenomenon you described. please provide more detail information.

**Comment by laolihaile** [comment]
> 我无法重现您描述的现象。请提供更多详细信息。



> I can't reproduce the phenomenon you described. please provide more detail information.

thank you very much,  I solve it
