### ISSUE TITLE
Tensorflow build script error

### ISSUE THREAD

**Issue by zye1996** [terryky/tflite_gles_app#25]
Hi, I tried to build TensorFlow using the given script. When building the tflite GPU delegate, the following command failed in the script:

```bazel build -s -c opt --copt="-DMESA_EGL_NO_X11_HEADERS" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so 2>&1 | tee -a log_build_delegate.txt``` with a bunch of ```error: expected unqualified-id before 'int'```

and I resolved this by replacing it with:
```bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 tensorflow/lite/delegates/gpu:gl_delegate```

Is this related to my desktop configuration or there is a need to update the script in the repo? I am using ubuntu 20.04.

**Comment by terryky** [comment]
Thank you for informing me.
I could reproduced the error on Ubuntu20.
As described [this comment](https://github.com/google/mediapipe/issues/305#issuecomment-564315361), I added `EGL_NO_X11` into the build script.
