### ISSUE TITLE
DBFace compile error

### ISSUE THREAD

**Issue by MyraBaba** [terryky/tflite_gles_app#32]
Hi,

for make DBFACE gives error:

/usr/bin/ld: /home/pi/bcwork/tflite_gles_app/common/util_texture.o: in function `create_video_texture':
/home/pi/bcwork/tflite_gles_app/common/util_texture.c:259: undefined reference to `open_video_file'
/usr/bin/ld: /home/pi/bcwork/tflite_gles_app/common/util_texture.c:261: undefined reference to `get_video_dimension'
/usr/bin/ld: /home/pi/bcwork/tflite_gles_app/common/util_texture.c:262: undefined reference to `get_video_pixformat'
/usr/bin/ld: /home/pi/bcwork/tflite_gles_app/common/util_texture.c:265: undefined reference to `start_video_decode'
/usr/bin/ld: /home/pi/bcwork/tflite_gles_app/common/util_texture.o: in function `update_video_texture':
/home/pi/bcwork/tflite_gles_app/common/util_texture.c:277: undefined reference to `get_video_dimension'
/usr/bin/ld: /home/pi/bcwork/tflite_gles_app/common/util_texture.c:278: undefined reference to `get_video_pixformat'
/usr/bin/ld: /home/pi/bcwork/tflite_gles_app/common/util_texture.c:279: undefined reference to `get_video_buffer'

Best

**Comment by MyraBaba** [comment]
Solution:

add TARGET :  make -j4 TARGET_ENV=raspi4 

forgot it.

:)

**Comment by terryky** [comment]
The issue seems to have been solved.
