### ISSUE TITLE
Cannot reproduce posnet with GPU Delegate V2 on Devboard

### ISSUE THREAD

**Issue by AlexTraan** [terryky/tflite_gles_app#4]
Hi Terryky san,

Thank you for your value repository.

I am trying to reproduce Posenet with GPU Delegate V2 on Devboard, but faced error when build app as below:
"/usr/bin/ld: skipping incompatible /home/mendel/work/static_lib/aarch64/libtensorflowlite_gpu_delegate.so when searching for -ltensorflowlite_gpu_delegate
/usr/bin/ld: cannot find -ltensorflowlite_gpu_delegate"

i put cross-compile tensorflowlite_gpu_deleage.so to /home/mendel/work/static_lib/aarch64.

After googled, i guess the problem come from libtensorflowlite_gpu_delegate.so not suitable build for Devboard.

This "bazel build -s -c opt --copt="-DMESA_EGL_NO_X11_HEADERS"  tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so 2>&1 | tee -a log_build_delegate.txt" build command not include target option for devboard aarch64, is this OK?

Can you give me any advice?

**Comment by terryky** [comment]
For aarch64, follow the steps in [this section](https://github.com/terryky/tflite_gles_app#22-build-for-jetson-nano-aarch64)

**Comment by terryky** [comment]
Please reopen if problem still exists.
