### ISSUE TITLE
[Posenet run inference on CPU, without GPU delegate] Abnormal display

### ISSUE THREAD

**Issue by AlexTraan** [terryky/tflite_gles_app#5]
Hi Terry san,

I can build to gl2posenet  binary file, but when run it, abnormal display as uploaded image.

can you advice anything to me?

![error](https://user-images.githubusercontent.com/22428496/85269635-5c08be80-b4a2-11ea-980e-67c0a447d408.jpg)

**Comment by terryky** [comment]
What is your target environment ?

**Comment by AlexTraan** [comment]
My target is Devboard

**Comment by terryky** [comment]
You may be able to get workaround this issue by adding the following code at the end of main.c.
However, I won't/can't support coral devboard because it's OpenGLES/OpenCL seems buggy.

```
        draw_dbgstr (strbuf, 10, 10);
+        {
+            unsigned int val;
+            glReadPixels (0, 0, 1, 1, GL_RGBA, GL_UNSIGNED_BYTE, &val);
+        }
         egl_swap();
    }
    return 0;
}
```

**Comment by terryky** [comment]
Please reopen if problem still exists.
